name: wizzup-github-io
version: 1.0.0
synopsis: wizzup website
maintainer: Wisut Hantanong
author: Wisut Hantanong
copyright: Wisut Hantanong
github: wizzup/wizzup.github.io

ghc-options:
- -Wall
- -Wno-type-defaults

dependencies:
  - base

executables:
  site:
    main: Site.hs
    ghc-options:
    - -threaded
    dependencies:
    - hakyll
    - containers
    - filepath
    - pandoc
